#!/bin/sh

[ -e debian/tests.home ] || mkdir debian/tests.home
export HOME="$(pwd)/debian/tests.home"
export XDG_RUNTIME_DIR=$(mktemp -d --suffix=runtime)

cleanup () {
    rm -rf debian/tests.home
    rm -rf "$XDG_RUNTIME_DIR"
}
trap cleanup EXIT

mkdir -p "$HOME"/.config || true

xvfb-run -a --server-args="-screen 0 1024x768x24" \
    dbus-run-session -- debian/tests/testsuite.xsession
